packages:
  - packages/*
  - primitives/*

catalog:
  vitest: 5.0.2
  '@vitest/coverage-v8': 5.0.2
  effect: 4.0.0

minimumReleaseAge: 1440
minimumReleaseAgeStrict: false
minimumReleaseAgeExclude:
  - effect@4.0.0
trustPolicy: no-downgrade

allowBuilds:
  '@swc/core': false
  esbuild: true
  lefthook: true
  protobufjs: false
  sqlite3: true
