export const instanceSamples: Readonly<Record<string, string>> = {
  Object: '({})',
  Function: '(function () { "use strict"; })',
  CallableFunction: '(function () { "use strict"; })',
  NewableFunction: '(function () { "use strict"; })',
  String: '""',
  Boolean: 'true',
  Number: '0',
  BigInt: '0n',
  Symbol: 'Symbol()',
  Array: '[]',
  ReadonlyArray: '[]',
  Date: 'new Date(0)',
  RegExp: '/x/',
  Error: 'new Error("", { cause: 0 })',
  Map: 'new Map()',
  ReadonlyMap: 'new Map()',
  Set: 'new Set()',
  ReadonlySet: 'new Set()',
  WeakMap: 'new WeakMap()',
  WeakSet: 'new WeakSet()',
  ArrayBuffer: 'new ArrayBuffer(8)',
  SharedArrayBuffer: 'new SharedArrayBuffer(8)',
  DataView: 'new DataView(new ArrayBuffer(8))',
  Int8Array: 'new Int8Array(1)',
  Uint8Array: 'new Uint8Array(1)',
  Uint8ClampedArray: 'new Uint8ClampedArray(1)',
  Int16Array: 'new Int16Array(1)',
  Uint16Array: 'new Uint16Array(1)',
  Int32Array: 'new Int32Array(1)',
  Uint32Array: 'new Uint32Array(1)',
  Float32Array: 'new Float32Array(1)',
  Float64Array: 'new Float64Array(1)',
  BigInt64Array: 'new BigInt64Array(1)',
  BigUint64Array: 'new BigUint64Array(1)',
  Generator: '(function* () {})()',
  IteratorObject: '[].values()',
  ArrayIterator: '[].values()',
  MapIterator: 'new Map().values()',
  SetIterator: 'new Set().values()',
  StringIterator: '""[Symbol.iterator]()',
  RegExpStringIterator: '"".matchAll(/x/g)',
};
