const introduction = [
  "A workflow coordinates the brain's functions, running them in order,",
  'deciding what happens next and waiting for input.',
  'Use workflow in conversation. The tools identify workflows with `primitive: orchestration`.',
  'Runs deterministic steps that call functions, branch, loop, run in parallel,',
  'wait, retry and catch errors, durably, until they end.',
  'A workflow definition is YAML in the Open Workflow Specification DSL 1.0.x (the CNCF',
  'Serverless Workflow DSL). For example, this one classifies a ticket with a reasoning function, drafts an',
  'escalation note with another only when the ticket is urgent, and then waits for the escalation to be approved:',
].join(' ');

export const workflowExample = [
  "document: {dsl: '1.0.3', namespace: support, name: triage, version: '1.0.0'}",
  'do:',
  '  - classify:',
  '      call: execute_spec',
  "      with: {primitive: inference, name: classify-ticket, input: {ticket: '${ .ticket }'}}",
  "      output: {as: '${ $input + {triage: .} }'}",
  '  - escalate:',
  '      if: .triage.urgency == "high"',
  '      call: execute_spec',
  "      with: {primitive: inference, name: draft-escalation, input: {ticket: '${ .ticket }'}}",
  "      output: {as: '${ $input + {note: .} }'}",
  '  - approval:',
  '      if: .note != null',
  '      listen: {to: {one: {with: {type: com.acme.escalation.approved}}}}',
  "      output: {as: '${ $input + {approved_by: .[0].by} }'}",
].join('\n');

const rules = [
  'A document is a mapping with document (dsl: 1.0.3, namespace, name, version, and an optional title and summary),',
  'an optional input (from, and an inline JSON Schema document), a do list of named tasks,',
  'an optional output (as, and a schema), an optional timeout, and optional use.errors, use.retries and',
  'use.timeouts to reuse.',
  'Steps use these DSL tasks: set; call execute_spec with { primitive, name, input } to run a function and take',
  'its output (a rejection is an error the workflow can catch); do; switch; for; fork of at most 32 branches',
  '(compete: true races the branches); try with catch (errors.with, when, exceptWhen, retry with delay, backoff,',
  'jitter and limits, and do); wait; raise; emit, which publishes an event to the brain (emit.event.with takes',
  'a type and a source, and no id: the brain gives the event one); and listen for events, those sent to the run',
  'with send_execution_event and, for a filter whose type is written out, those published to the brain.',
  'An optional schedule gives the workflow a trigger, so that the brain runs it on its own: schedule.on takes one',
  'filter, or any of a list, each naming the type of its events, and starts a run for every event of the brain',
  'that matches, with a list of that event as its input; schedule.cron takes five fields, minute, hour, day of month,',
  'month and day of week, in UTC, and schedule.every a duration of at least a minute, and each starts a run at every',
  'due time, with { schedule: { due } } as its input, skipping a time while the run before still runs.',
  'A run its trigger starts runs as the brain itself.',
  'Data flows through the tasks: a task takes the output of the task before it as its input, the first the input',
  'of the workflow, and . is that input in its expressions; a task whose if does not hold hands its input on unchanged.',
  'output.as shapes what a task hands on, with . as what the task produced and $input as its input, so',
  '${ $input + {triage: .} } keeps what came before; export.as sets $context, which later tasks read;',
  '$workflow.input is the input of the workflow in every task.',
  'call execute_spec produces the output of the function it ran: the text, or the JSON value, a reasoning function',
  'answered. listen produces a list with the data of each event it consumed.',
  'Task lists nest at most 64 levels deep. A workflow runs for at most the time the runtime is set to allow,',
  '30 days unless told otherwise; a wait or timeout longer than that is rejected, and one computed longer fails',
  'the workflow. An expression may do a bounded amount of work, about one pass over a few megabytes of data;',
  'more fails the workflow with a runtime error.',
  'Flow directives: then continue, exit, end, or the name of a task in the same list.',
  'Expressions are jq, enclosed in ${ }; if, when, for.in and while may also be written bare.',
  'Quote an expression that sits inside a {...} flow mapping, as above, or YAML reads its braces.',
  'Not allowed: run, call of http, grpc, openapi, asyncapi, a2a or mcp, catalogs, extensions,',
  'reusable functions, secrets, authentications, schedule.after, task schemas, executing another workflow,',
  'and the jq builtins localtime and strflocaltime.',
  'A run starts the workflow and answers started; get_execution shows it settled when the workflow ends:',
  'succeeded with its output, rejected when an error is not caught (invalid_input for a 4xx status other than',
  '408 and 429, unavailable otherwise), or failed.',
].join(' ');

export const workflowDescription = `${introduction}\n\n${workflowExample}\n\n${rules}`;
